# Generated by Django 5.1.3 on 2024-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.TextField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
