# Generated by Django 5.1.3 on 2024-11-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0002_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
