# Generated by Django 5.1.3 on 2024-11-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.TextField(),
        ),
    ]
