# Generated by Django 5.1.3 on 2024-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0007_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
