# Generated by Django 5.1.3 on 2024-11-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0008_alter_contact_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
    ]
