# Generated by Django 5.1.3 on 2024-11-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0010_comment_post_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="phone",
            new_name="website",
        ),
    ]
