# Generated by Django 5.1.3 on 2024-11-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0012_remove_post_comment_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
