# Generated by Django 5.1.3 on 2024-11-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0013_post_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
