# Generated by Django 5.1.3 on 2024-11-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0016_travelled_post_travelled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="travelled",
        ),
        migrations.DeleteModel(
            name="Travelled",
        ),
    ]
