# Generated by Django 5.1.3 on 2024-11-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0017_remove_post_travelled_delete_travelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
    ]
