# Generated by Django 5.1.3 on 2024-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balitassap", "0018_comment_comments_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comments_count",
        ),
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
    ]
